version: "3.9"

services:
  refresher-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: refresher-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://admin:admin123@mongodb:27017
    volumes:
      - .:/app
    depends_on:
      - mongodb
    command: uvicorn refresher_backend:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@mongodb:27017/
